// Blog slug redirects (old rewritten/duplicate slugs -> canonical). Lives here,
// not in public/_redirects, because Cloudflare caps _redirects at 100 rules.
// Keys are paths with NO trailing slash; the handler normalizes before lookup.
// General site path redirects (retired pages -> canonical). Keys have NO trailing slash.
export const PATH_REDIRECTS = {
  "/claim-50": "/demo/", // the book-a-meeting funnel now lives at /demo/; old /claim-50/ links redirect here

  // Generic-SaaS pivot (Phase 3, 2026-09): retired the 17 trade landing pages,
  // the /industries/ hub, the 4 platform /compare/ pages + hub, and /lead-math —
  // all built around a home-service ICP the site no longer targets. GSC showed
  // 0 clicks across every trade page in the 28d window before retirement, so
  // there's no organic equity to preserve — these are plain redirects, not
  // 1:1 content matches.
  "/general-contractor-leads": "/features/",
  "/handyman-leads": "/features/",
  "/tree-removal-leads": "/features/",
  "/hvac-leads": "/features/",
  "/plumber-leads": "/features/",
  "/locksmith-leads": "/features/",
  "/electrician-leads": "/features/",
  "/roofing-leads": "/features/",
  "/painter-leads": "/features/",
  "/deck-fence-leads": "/features/",
  "/garage-door-leads": "/features/",
  "/appliance-repair-leads": "/features/",
  "/house-cleaning-leads": "/features/",
  "/pest-control-leads": "/features/",
  "/power-washing-leads": "/features/",
  "/lawn-care-leads": "/features/",
  "/mobile-car-service-leads": "/features/",
  "/industries": "/features/",
  "/resources/compare": "/pricing/",
  "/resources/compare/thumbtack": "/pricing/",
  "/resources/compare/angi": "/pricing/",
  "/resources/compare/homeadvisor": "/pricing/",
  "/resources/compare/google-local-service-ads": "/pricing/",
  "/lead-math": "/pricing/",

  // Guide/explainer corpus (2026-09): retired the 3 pieces whose entire premise
  // was Google Local Service Ads / neighbor-marketing-after-a-job — concepts
  // specific to local home-service businesses, not the generic-SaaS ICP.
  "/resources/how-to-guides/win-google-local-service-ads": "/resources/how-to-guides/",
  "/resources/how-to-guides/market-to-neighbors-after-every-job": "/resources/how-to-guides/",
  "/resources/plain-language-explainers/what-are-google-local-services-ads": "/resources/plain-language-explainers/",
  "/resources/plain-language-explainers/what-is-email-marketing-for-contractors": "/resources/plain-language-explainers/what-is-email-marketing-for-businesses/",
  "/resources/plain-language-explainers/what-is-sms-marketing-for-contractors": "/resources/plain-language-explainers/what-is-sms-marketing-for-businesses/",
};

export const BLOG_REDIRECTS = {
  // Generic-SaaS pivot (2026-09): renamed 17 blog slugs that baked "contractor"
  // into the URL itself; content generalized in place, redirects cover old slugs.
  "/resources/blog/contractor-crm-data-hygiene": "/resources/blog/business-crm-data-hygiene/",
  "/resources/blog/how-contractors-rank-in-google-map-pack": "/resources/blog/how-businesses-rank-in-google-map-pack/",
  "/resources/blog/how-to-nurture-contractor-leads-not-ready-to-buy": "/resources/blog/how-to-nurture-leads-not-ready-to-buy/",
  "/resources/blog/how-to-set-up-retargeting-contractor-website": "/resources/blog/how-to-set-up-retargeting-business-website/",
  "/resources/blog/is-retargeting-legal-for-contractors": "/resources/blog/is-retargeting-legal-for-businesses/",
  "/resources/blog/most-contractor-leads-come-in-after-hours": "/resources/blog/most-leads-come-in-after-hours/",
  "/resources/blog/new-years-week-the-quiet-reason-your-general-contractors-phone-isnt-ringing-enough": "/resources/blog/new-years-week-the-quiet-reason-your-phone-isnt-ringing-enough/",
  "/resources/blog/the-general-contractors-rush-is-coming-stop-letting-ready-buyers-leave-anonymous": "/resources/blog/the-busy-season-rush-is-coming-stop-letting-ready-buyers-leave-anonymous/",
  "/resources/blog/what-a-missed-call-actually-costs-a-contractor": "/resources/blog/what-a-missed-call-actually-costs-a-business/",
  "/resources/blog/what-the-ftc-homeadvisor-order-teaches-contractors-about-leads": "/resources/blog/what-the-ftc-homeadvisor-order-teaches-businesses-about-leads/",
  "/resources/blog/why-a-slow-website-loses-contractor-jobs": "/resources/blog/why-a-slow-website-loses-you-business/",
  "/resources/blog/what-privacy-violations-cost-contractors": "/resources/blog/what-privacy-violations-cost-businesses/",
  "/resources/blog/who-owns-your-contractor-leads": "/resources/blog/who-owns-your-leads/",
  "/resources/blog/why-general-contractors-lose-their-best-leads-during-tax-day-crunch-and-how-to-keep-them": "/resources/blog/why-businesses-lose-their-best-leads-during-tax-day-crunch-and-how-to-keep-them/",
  "/resources/blog/why-gut-feel-lead-triage-fails-contractors": "/resources/blog/why-gut-feel-lead-triage-fails-businesses/",
  "/resources/blog/why-online-reviews-win-contractor-jobs": "/resources/blog/why-online-reviews-win-you-business/",
  "/resources/blog/why-shared-leads-waste-contractor-time": "/resources/blog/why-shared-leads-waste-business-time/",

  // Generic-SaaS pivot (2026-09), round 2: 9 more slug renames found in the
  // wider blog-corpus sweep.
  "/resources/blog/roofing-google-ads-cost-per-lead": "/resources/blog/google-ads-cost-per-lead/",
  "/resources/blog/how-roofers-capture-quote-shoppers-who-never-fill-out-a-form": "/resources/blog/how-businesses-capture-quote-shoppers-who-never-fill-out-a-form/",
  "/resources/blog/how-roofers-turn-repeat-website-visitors-into-booked-jobs": "/resources/blog/how-businesses-turn-repeat-website-visitors-into-closed-deals/",
  "/resources/blog/house-cleaning-lead-lifetime-value": "/resources/blog/lead-lifetime-value/",
  "/resources/blog/roofing-website-audit-checklist": "/resources/blog/website-audit-checklist/",
  "/resources/blog/what-a-lost-hvac-lead-actually-costs-you": "/resources/blog/what-a-lost-lead-actually-costs-you/",
  "/resources/blog/what-a-roofers-website-trail-reveals-about-a-lead": "/resources/blog/what-a-website-trail-reveals-about-a-lead/",
  "/resources/blog/what-every-hvac-pro-should-know-about-the-shoppers-who-visit-and-vanish": "/resources/blog/what-every-business-should-know-about-the-shoppers-who-visit-and-vanish/",
  "/resources/blog/your-busiest-hvac-season-is-also-your-biggest-lead-leak-heres-the-fix": "/resources/blog/your-busiest-season-is-also-your-biggest-lead-leak-heres-the-fix/",

  // Generic-SaaS pivot (2026-09): retired 27 blog articles whose entire premise
  // was a trade+season/holiday combo that doesn't generalize (hurricane season,
  // Groundhog Day, tax season for plumbers, etc.) — zero organic traffic, no
  // content to preserve.
  "/resources/blog/cyber-monday-giving-season-turn-electrical-website-lookers-into-booked-jobs-on-the-same-ad-budget": "/resources/blog/",
  "/resources/blog/daylight-saving-ends-first-freeze-how-plumbers-can-catch-the-homeowners-already-pricing-the-job": "/resources/blog/",
  "/resources/blog/deep-winter-freeze-how-plumbers-can-catch-the-homeowners-already-pricing-the-job": "/resources/blog/",
  "/resources/blog/dog-days-of-summer-turn-power-washing-website-lookers-into-booked-jobs-on-the-same-ad-budget": "/resources/blog/",
  "/resources/blog/early-summer-heat-returns-how-hvac-pros-can-catch-the-homeowners-already-pricing-the-job": "/resources/blog/",
  "/resources/blog/earth-day-turn-lawn-care-website-lookers-into-booked-jobs-on-the-same-ad-budget": "/resources/blog/",
  "/resources/blog/end-of-summer-push-playbook-for-painters-recover-the-98-who-dont-call": "/resources/blog/",
  "/resources/blog/fall-home-prep-playbook-for-handymen-recover-the-98-who-dont-call": "/resources/blog/",
  "/resources/blog/fall-maintenance-kickoff-the-tree-removal-quote-shoppers-on-your-site-you-never-knew-were-there": "/resources/blog/",
  "/resources/blog/fathers-day-first-heat-wave-how-hvac-pros-can-catch-the-homeowners-already-pricing-the-job": "/resources/blog/",
  "/resources/blog/first-day-of-fall-q3-close-turn-hvac-website-lookers-into-booked-jobs-on-the-same-ad-budget": "/resources/blog/",
  "/resources/blog/house-cleaners-meet-your-hidden-halloween-pipeline": "/resources/blog/",
  "/resources/blog/independence-day-july-4-the-hvac-quote-shoppers-on-your-site-you-never-knew-were-there": "/resources/blog/",
  "/resources/blog/late-winter-tax-season-playbook-for-plumbers-recover-the-98-who-dont-call": "/resources/blog/",
  "/resources/blog/lawn-care-pros-meet-your-hidden-memorial-day-summer-kickoff-pipeline": "/resources/blog/",
  "/resources/blog/lawn-care-pros-meet-your-hidden-st-patricks-first-day-of-spring-pipeline": "/resources/blog/",
  "/resources/blog/lead-scoring-for-roofers-which-storm-leads-to-work-first": "/resources/blog/",
  "/resources/blog/plumbers-meet-your-hidden-new-year-planning-resolutions-pipeline": "/resources/blog/",
  "/resources/blog/pre-christmas-year-end-playbook-for-handymen-recover-the-98-who-dont-call": "/resources/blog/",
  "/resources/blog/pre-labor-day-how-hvac-pros-can-catch-the-homeowners-already-pricing-the-job": "/resources/blog/",
  "/resources/blog/pre-mothers-day-playbook-for-mobile-detailers-recover-the-98-who-dont-call": "/resources/blog/",
  "/resources/blog/pre-thanksgiving-the-house-cleaning-quote-shoppers-on-your-site-you-never-knew-were-there": "/resources/blog/",
  "/resources/blog/pre-valentines-turn-electrical-website-lookers-into-booked-jobs-on-the-same-ad-budget": "/resources/blog/",
  "/resources/blog/roofers-meet-your-hidden-atlantic-hurricane-peak-pipeline": "/resources/blog/",
  "/resources/blog/spring-peak-the-deck-fence-quote-shoppers-on-your-site-you-never-knew-were-there": "/resources/blog/",
  "/resources/blog/spring-ramp-up-how-pest-control-pros-can-catch-the-homeowners-already-pricing-the-job": "/resources/blog/",
  "/resources/blog/tax-season-prep-begins-the-locksmith-quote-shoppers-on-your-site-you-never-knew-were-there": "/resources/blog/",

  // Generic-SaaS pivot (2026-09): consolidated 5 templates that were each
  // written 3-5x, once per trade, into a single generalized canonical article.
  // The trade-specific copies redirect to the surviving generalized version.
  "/resources/blog/daylight-saving-begins-the-quiet-reason-your-power-washing-phone-isnt-ringing-enough": "/resources/blog/new-years-week-the-quiet-reason-your-phone-isnt-ringing-enough/",
  "/resources/blog/late-summer-home-projects-the-quiet-reason-your-deck-fence-phone-isnt-ringing-enough": "/resources/blog/new-years-week-the-quiet-reason-your-phone-isnt-ringing-enough/",
  "/resources/blog/pre-halloween-the-quiet-reason-your-electrical-phone-isnt-ringing-enough": "/resources/blog/new-years-week-the-quiet-reason-your-phone-isnt-ringing-enough/",
  "/resources/blog/pre-memorial-day-the-quiet-reason-your-deck-fence-phone-isnt-ringing-enough": "/resources/blog/new-years-week-the-quiet-reason-your-phone-isnt-ringing-enough/",
  "/resources/blog/why-appliance-repair-pros-lose-their-best-leads-during-thanksgiving-black-friday-and-how-to-keep-them": "/resources/blog/why-businesses-lose-their-best-leads-during-tax-day-crunch-and-how-to-keep-them/",
  "/resources/blog/why-garage-door-pros-lose-their-best-leads-during-groundhog-day-big-game-and-how-to-keep-them": "/resources/blog/why-businesses-lose-their-best-leads-during-tax-day-crunch-and-how-to-keep-them/",
  "/resources/blog/why-pest-control-pros-lose-their-best-leads-during-mid-summer-heat-and-how-to-keep-them": "/resources/blog/why-businesses-lose-their-best-leads-during-tax-day-crunch-and-how-to-keep-them/",
  "/resources/blog/why-roofers-lose-their-best-leads-during-peak-hurricane-season-and-how-to-keep-them": "/resources/blog/why-businesses-lose-their-best-leads-during-tax-day-crunch-and-how-to-keep-them/",
  "/resources/blog/your-busiest-lawn-care-season-is-also-your-biggest-lead-leak-heres-the-fix": "/resources/blog/your-busiest-season-is-also-your-biggest-lead-leak-heres-the-fix/",
  "/resources/blog/your-busiest-mobile-car-service-season-is-also-your-biggest-lead-leak-heres-the-fix": "/resources/blog/your-busiest-season-is-also-your-biggest-lead-leak-heres-the-fix/",
  "/resources/blog/your-busiest-pest-control-season-is-also-your-biggest-lead-leak-heres-the-fix": "/resources/blog/your-busiest-season-is-also-your-biggest-lead-leak-heres-the-fix/",
  "/resources/blog/your-busiest-roofing-season-is-also-your-biggest-lead-leak-heres-the-fix": "/resources/blog/your-busiest-season-is-also-your-biggest-lead-leak-heres-the-fix/",
  "/resources/blog/what-every-appliance-repair-pro-should-know-about-the-shoppers-who-visit-and-vanish": "/resources/blog/what-every-business-should-know-about-the-shoppers-who-visit-and-vanish/",
  "/resources/blog/what-every-house-cleaning-pro-should-know-about-the-shoppers-who-visit-and-vanish": "/resources/blog/what-every-business-should-know-about-the-shoppers-who-visit-and-vanish/",
  "/resources/blog/what-every-tree-removal-pro-should-know-about-the-shoppers-who-visit-and-vanish": "/resources/blog/what-every-business-should-know-about-the-shoppers-who-visit-and-vanish/",
  "/resources/blog/the-handyman-rush-is-coming-stop-letting-ready-buyers-leave-anonymous": "/resources/blog/the-busy-season-rush-is-coming-stop-letting-ready-buyers-leave-anonymous/",
  "/resources/blog/the-painting-rush-is-coming-stop-letting-ready-buyers-leave-anonymous": "/resources/blog/the-busy-season-rush-is-coming-stop-letting-ready-buyers-leave-anonymous/",

  "/resources/blog/a-signed-receipt-on-every-lead-why-consent-records-protect-your-shop-2": "/resources/blog/do-bought-leads-come-with-proof-of-consent/",
  "/resources/blog/a-signed-receipt-on-every-lead-why-consent-records-protect-your-shop-3": "/resources/blog/what-the-ftc-homeadvisor-order-teaches-businesses-about-leads/",
  "/resources/blog/a-signed-receipt-on-every-lead-why-consent-records-protect-your-shop-4": "/resources/blog/which-privacy-laws-require-proof-of-lead-consent/",
  "/resources/blog/capturing-the-98-who-will-never-fill-out-your-form-2": "/resources/blog/what-anonymous-website-traffic-is-costing-you/",
  "/resources/blog/capturing-the-98-who-will-never-fill-out-your-form-3": "/resources/blog/how-businesses-capture-quote-shoppers-who-never-fill-out-a-form/",
  "/resources/blog/capturing-the-98-who-will-never-fill-out-your-form-4": "/resources/blog/how-to-vet-a-compliant-visitor-identification-tool/",
  "/resources/blog/capturing-the-98-who-will-never-fill-out-your-form-5": "/resources/blog/ways-to-capture-website-visitors-who-dont-convert/",
  "/resources/blog/consent-first-vs-buy-a-list-2": "/resources/blog/is-buying-a-lead-list-legal/",
  "/resources/blog/contact-form-is-your-competitor-2": "/resources/blog/why-homeowners-abandon-your-contact-form/",
  "/resources/blog/cost-per-lead-vs-cost-per-job-2": "/resources/blog/how-many-leads-do-you-need-to-hit-your-revenue-goal/",
  "/resources/blog/crm-only-as-good-as-inputs-2": "/resources/blog/business-crm-data-hygiene/",
  "/resources/blog/follow-up-window-wins-jobs-2": "/resources/blog/answer-leads-faster-instead-of-buying-more/",
  "/resources/blog/follow-up-window-wins-jobs-3": "/resources/blog/fast-follow-up-without-breaking-the-law/",
  "/resources/blog/from-anonymous-visitor-to-your-crm-in-one-clean-hand-off-2": "/resources/blog/the-real-cost-of-leads-that-never-reach-your-crm/",
  "/resources/blog/from-anonymous-visitor-to-your-crm-in-one-clean-hand-off-3": "/resources/blog/connecting-recovered-leads-to-your-field-service-crm/",
  "/resources/blog/from-anonymous-visitor-to-your-crm-in-one-clean-hand-off-4": "/resources/blog/an-email-alert-is-not-lead-delivery/",
  "/resources/blog/get-more-leads-no-extra-spend-2": "/resources/blog/recovered-leads-only-convert-when-you-respond-fast/",
  "/resources/blog/get-more-leads-no-extra-spend-3": "/resources/blog/the-high-intent-visitors-leaving-your-site-anonymous/",
  "/resources/blog/get-more-reviews-without-begging-2": "/resources/blog/why-online-reviews-win-you-business/",
  "/resources/blog/get-more-reviews-without-begging-3": "/resources/blog/how-to-respond-to-customer-reviews/",
  "/resources/blog/hot-warm-or-just-browsing-sorting-leads-so-you-work-the-right-ones-first-2": "/resources/blog/lead-scoring-for-roofers-which-storm-leads-to-work-first/",
  "/resources/blog/hot-warm-or-just-browsing-sorting-leads-so-you-work-the-right-ones-first-3": "/resources/blog/the-cost-of-working-leads-in-the-wrong-order/",
  "/resources/blog/hot-warm-or-just-browsing-sorting-leads-so-you-work-the-right-ones-first-4": "/resources/blog/why-gut-feel-lead-triage-fails-businesses/",
  "/resources/blog/hot-warm-or-just-browsing-sorting-leads-so-you-work-the-right-ones-first-5": "/resources/blog/route-scored-leads-into-your-follow-up-automation/",
  "/resources/blog/local-seo-for-busy-pros-2": "/resources/blog/how-businesses-rank-in-google-map-pack/",
  "/resources/blog/missed-calls-cost-you-jobs-2": "/resources/blog/what-a-missed-call-actually-costs-a-business/",
  "/resources/blog/missed-calls-cost-you-jobs-3": "/resources/blog/most-leads-come-in-after-hours/",
  "/resources/blog/more-traffic-wrong-goal-2": "/resources/blog/how-to-measure-website-capture-rate/",
  "/resources/blog/more-traffic-wrong-goal-3": "/resources/blog/ranking-first-but-not-booking-jobs/",
  "/resources/blog/never-fear-where-did-you-get-my-info-2": "/resources/blog/why-lead-resellers-cant-tell-you-where-they-got-your-info/",
  "/resources/blog/one-page-website-audit-2": "/resources/blog/why-a-slow-website-loses-you-business/",
  "/resources/blog/one-page-website-audit-3": "/resources/blog/website-audit-checklist/",
  "/resources/blog/read-the-trail-knowing-what-a-homeowner-looked-at-before-they-call-2": "/resources/blog/is-it-legal-to-track-what-pages-a-visitor-viewed/",
  "/resources/blog/read-the-trail-knowing-what-a-homeowner-looked-at-before-they-call-3": "/resources/blog/blind-shared-leads-vs-website-leads-with-context/",
  "/resources/blog/read-the-trail-knowing-what-a-homeowner-looked-at-before-they-call-4": "/resources/blog/how-to-turn-browse-history-into-follow-up-templates/",
  "/resources/blog/read-the-trail-knowing-what-a-homeowner-looked-at-before-they-call-5": "/resources/blog/what-a-website-trail-reveals-about-a-lead/",
  "/resources/blog/referral-engine-that-runs-itself-2": "/resources/blog/referrals-vs-buying-leads-the-real-cost/",
  "/resources/blog/referral-engine-that-runs-itself-3": "/resources/blog/turn-online-reviews-into-a-referral-engine/",
  "/resources/blog/retargeting-without-jargon-2": "/resources/blog/how-to-set-up-retargeting-business-website/",
  "/resources/blog/see-whos-on-your-site-right-now-without-a-single-form-fill-2": "/resources/blog/how-to-calculate-wasted-ad-spend/",
  "/resources/blog/see-whos-on-your-site-right-now-without-a-single-form-fill-3": "/resources/blog/visitor-identification-without-fingerprinting/",
  "/resources/blog/see-whos-on-your-site-right-now-without-a-single-form-fill-4": "/resources/blog/seeing-website-visitors-in-real-time/",
  "/resources/blog/see-whos-on-your-site-right-now-without-a-single-form-fill-5": "/resources/blog/what-data-is-in-a-consented-visitor-lead/",
  "/resources/blog/shared-vs-exclusive-leads-math-2": "/resources/blog/do-shared-leads-have-consent/",
  "/resources/blog/shared-vs-exclusive-leads-math-3": "/resources/blog/when-shared-leads-make-sense/",
  "/resources/blog/slow-season-cash-flow-2": "/resources/blog/slow-season-marketing-budget-math/",
  "/resources/blog/slow-season-cash-flow-3": "/resources/blog/slow-season-is-a-capture-problem/",
  "/resources/blog/state-privacy-patchwork-2": "/resources/blog/what-privacy-violations-cost-businesses/",
  "/resources/blog/stop-tire-kickers-eating-time-2": "/resources/blog/why-shared-leads-waste-business-time/",
  "/resources/blog/tcpa-plain-english-2": "/resources/blog/what-counts-as-tcpa-consent/",
  "/resources/blog/texas-tdpsa-for-your-website-2": "/resources/blog/answering-tdpsa-data-requests-from-your-customers/",
  "/resources/blog/the-98-percent-problem-2": "/resources/blog/why-website-visitors-leave-without-converting/",
  "/resources/blog/the-cookie-banner-that-keeps-you-legal-and-unlocks-every-lead-2": "/resources/blog/website-tracking-lawsuits-and-the-consent-banner-fix/",
  "/resources/blog/the-cookie-banner-that-keeps-you-legal-and-unlocks-every-lead-3": "/resources/blog/consent-banner-vs-contact-form/",
  "/resources/blog/the-cookie-banner-that-keeps-you-legal-and-unlocks-every-lead-4": "/resources/blog/what-makes-a-consent-banner-legally-compliant/",
  "/resources/blog/the-general-contractors-rush-is-coming-stop-letting-ready-buyers-leave-anonymous-2": "/resources/blog/why-homeowners-research-remodels-before-calling/",
  "/resources/blog/three-visits-before-they-called-2": "/resources/blog/how-to-nurture-leads-not-ready-to-buy/",
  "/resources/blog/turn-one-website-visit-into-an-ad-audience-that-books-jobs-2": "/resources/blog/is-retargeting-legal-for-businesses/",
  "/resources/blog/turn-one-website-visit-into-an-ad-audience-that-books-jobs-3": "/resources/blog/retargeting-vs-buying-shared-leads-cost/",
  "/resources/blog/turn-one-website-visit-into-an-ad-audience-that-books-jobs-4": "/resources/blog/how-to-set-up-consent-first-retargeting/",
  "/resources/blog/turn-one-website-visit-into-an-ad-audience-that-books-jobs-5": "/resources/blog/why-more-ad-spend-wont-fix-your-lead-problem/",
  "/resources/blog/website-storefront-lights-off-2": "/resources/blog/is-visitor-identification-legal/",
  "/resources/blog/website-storefront-lights-off-3": "/resources/blog/first-to-follow-up-wins-the-job/",
  "/resources/blog/what-every-house-cleaning-pro-should-know-about-the-shoppers-who-visit-and-vanish-2": "/resources/blog/lead-lifetime-value/",
  "/resources/blog/what-exclusive-lead-is-worth-2": "/resources/blog/exclusive-leads-high-ticket-jobs/",
  "/resources/blog/what-exclusive-lead-is-worth-3": "/resources/blog/who-owns-your-leads/",
  "/resources/blog/when-a-past-visitor-comes-back-you-should-be-the-first-to-know-2": "/resources/blog/is-it-legal-to-track-when-a-website-visitor-returns/",
  "/resources/blog/when-a-past-visitor-comes-back-you-should-be-the-first-to-know-3": "/resources/blog/return-visitor-lead-vs-buying-shared-leads-cost/",
  "/resources/blog/when-a-past-visitor-comes-back-you-should-be-the-first-to-know-4": "/resources/blog/how-businesses-turn-repeat-website-visitors-into-closed-deals/",
  "/resources/blog/when-a-past-visitor-comes-back-you-should-be-the-first-to-know-5": "/resources/blog/how-to-set-up-return-visit-alerts-for-your-contracting-business/",
  "/resources/blog/why-google-ads-feel-expensive-2": "/resources/blog/lsa-vs-search-ads-cost-per-lead/",
  "/resources/blog/why-google-ads-feel-expensive-3": "/resources/blog/google-ads-cost-per-lead/",
  "/resources/blog/your-busiest-hvac-season-is-also-your-biggest-lead-leak-heres-the-fix-2": "/resources/blog/what-a-lost-lead-actually-costs-you/"
};
